# Generated by Django 5.2.7 on 2026-06-22 20:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0004_user_dataset_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderModelRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('foundation', 'Foundation bundle')], default='foundation', max_length=32)),
                ('version', models.CharField(max_length=120, unique=True)),
                ('training_data_checksum', models.CharField(max_length=64)),
                ('artifact_checksum', models.CharField(max_length=64)),
                ('artifact', models.BinaryField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('label_catalog', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('kind',), name='builder_model_active_kind_uniq')],
            },
        ),
        migrations.CreateModel(
            name='BuildRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('purpose', models.TextField()),
                ('privacy_acknowledged', models.BooleanField(default=False)),
                ('requested_dataset_ids', models.JSONField(blank=True, default=list)),
                ('parsed_requirements', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('planning', 'Planning'), ('ready', 'Ready'), ('building', 'Building'), ('succeeded', 'Succeeded'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_build_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BuildCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=6, max_digits=8)),
                ('selected', models.BooleanField(default=False)),
                ('matched_labels', models.JSONField(blank=True, default=list)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builder_candidates', to='datasets.datasetversion')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='builder.buildrequest')),
            ],
            options={
                'ordering': ('-score', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BuildRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('retrying', 'Retrying'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='queued', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('output_row_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('output_checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_output_runs', to='datasets.dataset')),
                ('output_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_output_runs', to='datasets.datasetversion')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='builder.buildrequest')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_build_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DatasetAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('unsupported', 'Unsupported')], default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('schema_fingerprint', models.CharField(blank=True, max_length=64)),
                ('dataset_text_checksum', models.CharField(blank=True, max_length=64)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='builder_analysis', to='datasets.datasetversion')),
                ('model_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dataset_analyses', to='builder.buildermodelrelease')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DatasetTableSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=1000)),
                ('format', models.CharField(max_length=24)),
                ('logical_name', models.CharField(max_length=255)),
                ('row_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('column_count', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('schema_fingerprint', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='builder.datasetanalysis')),
            ],
            options={
                'ordering': ('relative_path',),
            },
        ),
        migrations.CreateModel(
            name='DatasetFieldSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=500)),
                ('physical_type', models.CharField(max_length=255)),
                ('nullable', models.BooleanField(default=True)),
                ('semantic_type', models.CharField(choices=[('patient_id', 'Patient identifier'), ('subject_id', 'Subject identifier'), ('study_id', 'Study identifier'), ('encounter_id', 'Encounter identifier'), ('image_id', 'Image identifier'), ('generic_id', 'Generic identifier'), ('age', 'Age'), ('sex', 'Sex'), ('city', 'City'), ('location', 'Location'), ('smoking_status', 'Smoking status'), ('diagnosis', 'Diagnosis'), ('cancer_status', 'Cancer status'), ('timestamp', 'Timestamp'), ('modality', 'Modality'), ('target', 'Target'), ('free_text', 'Free text'), ('numeric_measurement', 'Numeric measurement'), ('categorical', 'Categorical value'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('semantic_confidence', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('privacy_class', models.CharField(choices=[('non_sensitive', 'Non-sensitive'), ('sensitive', 'Sensitive'), ('quasi_identifier', 'Quasi-identifier'), ('direct_identifier', 'Direct identifier'), ('pseudonymous_identifier', 'Pseudonymous identifier')], default='non_sensitive', max_length=40)),
                ('join_candidate', models.BooleanField(default=False)),
                ('non_null_count', models.PositiveBigIntegerField(default=0)),
                ('distinct_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('null_fraction', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('unique_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('value_profile', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='builder.datasettableschema')),
            ],
            options={
                'ordering': ('ordinal',),
            },
        ),
        migrations.CreateModel(
            name='BuildInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('schema_fingerprint', models.CharField(max_length=64)),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builder_inputs', to='datasets.datasetversion')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='builder.buildrun')),
                ('join_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builder_join_inputs', to='builder.datasetfieldschema')),
                ('table_schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builder_inputs', to='builder.datasettableschema')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='DatasetTagPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(choices=[('anatomical_area', 'Anatomical area'), ('modality', 'Modality'), ('ml_task', 'ML task'), ('tag', 'Tag')], max_length=32)),
                ('value', models.CharField(max_length=100)),
                ('confidence', models.DecimalField(decimal_places=5, max_digits=6)),
                ('applied', models.BooleanField(default=False)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_predictions', to='builder.datasetanalysis')),
            ],
            options={
                'ordering': ('namespace', '-confidence', 'value'),
            },
        ),
        migrations.CreateModel(
            name='TransformationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('invalid', 'Invalid')], default='active', max_length=16)),
                ('plan', models.JSONField()),
                ('plan_checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_transformation_plans', to=settings.AUTH_USER_MODEL)),
                ('model_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transformation_plans', to='builder.buildermodelrelease')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='builder.buildrequest')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='PrivacyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('review_required', 'Review required')], max_length=24)),
                ('risk_level', models.CharField(max_length=16)),
                ('rules_version', models.CharField(max_length=64)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('excluded_fields', models.JSONField(blank=True, default=list)),
                ('join_policy', models.JSONField(blank=True, default=dict)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_assessment', to='builder.transformationplan')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='join_input', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineage', to='builder.buildrun')),
                ('input_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineage_outputs', to='datasets.datasetversion')),
                ('output_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_inputs', to='datasets.datasetversion')),
                ('transformation_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineage', to='builder.transformationplan')),
            ],
        ),
        migrations.AddField(
            model_name='buildrun',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='builder.transformationplan'),
        ),
        migrations.AddIndex(
            model_name='buildrequest',
            index=models.Index(fields=['user', '-created_at'], name='builder_req_user_idx'),
        ),
        migrations.AddIndex(
            model_name='buildrequest',
            index=models.Index(fields=['status', '-created_at'], name='builder_req_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='buildcandidate',
            constraint=models.UniqueConstraint(fields=('request', 'dataset_version'), name='builder_request_candidate_uniq'),
        ),
        migrations.AddIndex(
            model_name='datasetanalysis',
            index=models.Index(fields=['status', '-created_at'], name='builder_analysis_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasettableschema',
            constraint=models.UniqueConstraint(fields=('analysis', 'relative_path'), name='builder_analysis_table_path_uniq'),
        ),
        migrations.AddIndex(
            model_name='datasetfieldschema',
            index=models.Index(fields=['semantic_type', 'join_candidate'], name='builder_field_sem_join_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasetfieldschema',
            constraint=models.UniqueConstraint(fields=('table', 'ordinal'), name='builder_table_field_ordinal_uniq'),
        ),
        migrations.AddConstraint(
            model_name='datasetfieldschema',
            constraint=models.UniqueConstraint(fields=('table', 'name'), name='builder_table_field_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='buildinput',
            constraint=models.UniqueConstraint(fields=('run', 'dataset_version'), name='builder_run_input_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='buildinput',
            constraint=models.UniqueConstraint(fields=('run', 'position'), name='builder_run_input_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='datasettagprediction',
            constraint=models.UniqueConstraint(fields=('analysis', 'namespace', 'value'), name='builder_analysis_tag_pred_uniq'),
        ),
        migrations.AddConstraint(
            model_name='transformationplan',
            constraint=models.UniqueConstraint(fields=('request', 'version'), name='builder_request_plan_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='transformationplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('request',), name='builder_request_active_plan_uniq'),
        ),
        migrations.AddConstraint(
            model_name='datasetlineage',
            constraint=models.UniqueConstraint(fields=('output_version', 'input_version'), name='builder_lineage_output_input_uniq'),
        ),
        migrations.AddIndex(
            model_name='buildrun',
            index=models.Index(fields=['requested_by', '-created_at'], name='builder_run_user_idx'),
        ),
        migrations.AddIndex(
            model_name='buildrun',
            index=models.Index(fields=['status', '-created_at'], name='builder_run_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='buildrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running', 'retrying'))), fields=('request',), name='builder_request_active_run_uniq'),
        ),
    ]
