# Generated by Django 5.2.7 on 2026-06-21 20:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SourceDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=500)),
                ('source_url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_ref', models.CharField(blank=True, max_length=255)),
                ('license_name', models.CharField(blank=True, max_length=255)),
                ('license_names', models.JSONField(blank=True, default=list)),
                ('total_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('vote_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('view_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('usability_rating', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('remote_version', models.CharField(blank=True, max_length=100)),
                ('remote_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('summary_metadata', models.JSONField(blank=True, default=dict)),
                ('detail_metadata', models.JSONField(blank=True, default=dict)),
                ('detail_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('stale', 'Stale'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('detail_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('detail_source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('detail_error', models.TextField(blank=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='catalog.datasource')),
            ],
            options={
                'ordering': ('-remote_updated_at', '-id'),
                'indexes': [models.Index(fields=['source', '-remote_updated_at'], name='catalog_src_remote_idx'), models.Index(fields=['source', 'last_seen_at'], name='catalog_src_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='catalog_src_ext_id_uniq')],
            },
        ),
    ]
