# Generated by Django 5.2.7 on 2026-06-21 20:51

from django.db import migrations


def seed_kaggle_source(apps, schema_editor):
    DataSource = apps.get_model(
        "catalog",
        "DataSource",
    )

    DataSource.objects.update_or_create(
        slug="kaggle",
        defaults={
            "name": "Kaggle",
            "base_url": "https://www.kaggle.com",
            "is_enabled": True,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            seed_kaggle_source,
            migrations.RunPython.noop,
        ),
    ]
